"""
Unified Deployment Score (UDS) - Weighted Score Calculator
==========================================================
Step 2 of 2: This script computes weighted composite UDS scores from the
sub-scores (S1~S7) generated by '1. Create UDS Scores.py'.

Users can define custom weight profiles to emphasize different aspects:
  - Accuracy-strict: higher weight on S4 (accuracy retention)
  - Latency-first:   higher weight on S2 (latency efficiency)
  - Throughput-first: higher weight on S5 (offline throughput gain)

Two score types:
  - UDS_Basic (S1~S5): Core metrics, all devices included
  - UDS_Extended (S1~S7): Includes S6 (peak compute) & S7 (power efficiency),
    excludes devices without hardware specs (e.g., Apple M4 SoC)

Inputs:
  - UDS_scores_summary.csv  (output from Step 1)

Outputs:
  - UDS_cases_results.csv   : Full rankings for every weight profile
  - UDS_cases_winners.csv   : Winner device per profile
  - UDS_weight_profiles.csv : Weight definitions used

Author: AI-MicroBMT Team
"""

import pandas as pd
import numpy as np
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent / 'analysis_charts' / 'UDS metrics'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

CSV = OUTPUT_DIR / "UDS_scores_summary.csv"  # Read from output dir

df = pd.read_csv(CSV)

# Output CSV files
OUTPUT_UDS_CASES = OUTPUT_DIR / "UDS_cases_results.csv"  # Full results for all 16 cases
OUTPUT_UDS_WINNERS = OUTPUT_DIR / "UDS_cases_winners.csv"  # Winner only for each case
OUTPUT_WEIGHT_PROFILES = OUTPUT_DIR / "UDS_weight_profiles.csv"  # Weight definitions for all 16 cases

# 1) Auto-detect device column (typically 'device'/'hardware'/'Device', etc.)
device_col = None
for cand in ["device", "Device", "hardware", "Hardware", "accelerator", "Accelerator"]:
    if cand in df.columns:
        device_col = cand
        break
if device_col is None:
    # Assume first column is the device column
    device_col = df.columns[0]

# 2) Auto-map S1~S7 columns (adjust to match your CSV column names)
def find_col(prefix):
    # e.g., finds columns starting with 'S1', 'S1_coverage', etc.
    for c in df.columns:
        if str(c).startswith(prefix):
            return c
    raise KeyError(f"Cannot find column starting with {prefix}")

Scols = {f"S{i}": find_col(f"S{i}") for i in range(1, 8)}

# --------------------------
# Weight Definitions
# --------------------------

# UDS (S1~S5) - 4 profiles
UDS_profiles = {
    "UDS_AccuracyStrict": {"S1":0.15, "S2":0.20, "S3":0.15, "S4":0.30, "S5":0.20},
    "UDS_LatencyFirst":   {"S1":0.15, "S2":0.30, "S3":0.15, "S4":0.20, "S5":0.20},
    "UDS_ThptFirst":      {"S1":0.15, "S2":0.20, "S3":0.15, "S4":0.20, "S5":0.30},

    # Fixed input resolution variants (w3=0.0)
    "UDS_AccuracyStrict_with_fixed_inputRes": {"S1":0.18, "S2":0.24, "S3":0, "S4":0.34, "S5":0.24},
    "UDS_LatencyFirst_with_fixed_inputRes":   {"S1":0.18, "S2":0.34, "S3":0, "S4":0.24, "S5":0.24},
    "UDS_ThptFirst_with_fixed_inputRes":      {"S1":0.18, "S2":0.24, "S3":0, "S4":0.24, "S5":0.34},
}

# UDS_Extended (S1~S7) - 12 profiles
EXT_profiles = {
    # with both compute & power
    "EXT_AccStrict_Both": {"S1":0.13,"S2":0.13,"S3":0.13,"S4":0.18,"S5":0.13,"S6":0.15,"S7":0.15},
    "EXT_LatFirst_Both":  {"S1":0.13,"S2":0.18,"S3":0.13,"S4":0.13,"S5":0.13,"S6":0.15,"S7":0.15},
    "EXT_ThptFirst_Both": {"S1":0.13,"S2":0.13,"S3":0.13,"S4":0.13,"S5":0.18,"S6":0.15,"S7":0.15},

    # with both compute & power (w3=0.0)
    "EXT_AccStrict_Both_with_fixed_inputRes": {"S1":0.16,"S2":0.16,"S3":0,"S4":0.21,"S5":0.16,"S6":0.155,"S7":0.155},
    "EXT_LatFirst_Both_with_fixed_inputRes":  {"S1":0.16,"S2":0.21,"S3":0,"S4":0.16,"S5":0.16,"S6":0.155,"S7":0.155},
    "EXT_ThptFirst_Both_with_fixed_inputRes": {"S1":0.16,"S2":0.16,"S3":0,"S4":0.16,"S5":0.21,"S6":0.155,"S7":0.155},
    
    
    # # with both compute & power
    # "EXT_AccStrict_Both": {"S1":0.14,"S2":0.14,"S3":0.09,"S4":0.19,"S5":0.14,"S6":0.15,"S7":0.15},
    # "EXT_LatFirst_Both":  {"S1":0.14,"S2":0.19,"S3":0.09,"S4":0.14,"S5":0.14,"S6":0.15,"S7":0.15},
    # "EXT_ThptFirst_Both": {"S1":0.14,"S2":0.14,"S3":0.09,"S4":0.14,"S5":0.19,"S6":0.15,"S7":0.15},

    # # with both compute & power (w3=0.0)
    # "EXT_AccStrict_Both_with_fixed_inputRes": {"S1":0.16,"S2":0.16,"S3":0.0,"S4":0.21,"S5":0.16,"S6":0.155,"S7":0.155},
    # "EXT_LatFirst_Both_with_fixed_inputRes":  {"S1":0.16,"S2":0.21,"S3":0.0,"S4":0.16,"S5":0.16,"S6":0.155,"S7":0.155},
    # "EXT_ThptFirst_Both_with_fixed_inputRes": {"S1":0.16,"S2":0.16,"S3":0.0,"S4":0.16,"S5":0.21,"S6":0.155,"S7":0.155},
}
# --------------------------
# Helper Functions
# --------------------------


def weighted_score(row, weights, penalize_missing=True):
    """
    weights: dict like {"S1":0.2, "S2":0.2, ...}
    penalize_missing=True => treat NaN as 0
    False => exclude NaN entries and re-normalize remaining weights
    """
    vals = {}
    for k, w in weights.items():
        v = row[Scols[k]]
        vals[k] = v

    if penalize_missing:
        total = 0.0
        for k, w in weights.items():
            v = vals[k]
            if pd.isna(v):
                v = 0.0
            total += w * float(v)
        return total

    # renormalize among available metrics
    avail = {k: v for k, v in vals.items() if not pd.isna(v)}
    if len(avail) == 0:
        return np.nan
    wsum = sum(weights[k] for k in avail.keys())
    total = 0.0
    for k, v in avail.items():
        total += (weights[k] / wsum) * float(v)
    return total

def validate_weights(weights):
    """Validate that weights sum to 1.0 (within tolerance)"""
    total = sum(weights.values())
    assert abs(total - 1.0) < 0.001, f"Weights sum to {total}, not 1.0: {weights}"
    print(f"[OK] total : {total}, Weights validated: {weights}")

def run_profile(name, weights, extended=False, penalize_missing=True, exclude_devices=None):
    """
    Run UDS profile with given weights
    
    Args:
        name: Profile name
        weights: Dict of weights for S1-S7
        extended: Whether this is an extended profile (S1-S7)
        penalize_missing: How to handle NaN values
        exclude_devices: List of device names to exclude (e.g., ['Apple M4 CPU', 'Apple M4 ANE'])
    
    Returns:
        DataFrame with rankings and scores
    """
    validate_weights(weights)
    
    # Filter devices if needed
    tmp = df[[device_col] + [Scols[f"S{i}"] for i in range(1, 8)]].copy()
    if exclude_devices:
        tmp = tmp[~tmp[device_col].isin(exclude_devices)].copy()
    
    tmp["score"] = tmp.apply(lambda r: weighted_score(r, weights, penalize_missing), axis=1)
    tmp = tmp.sort_values("score", ascending=False).reset_index(drop=True)
    tmp.insert(0, "rank", np.arange(1, len(tmp)+1))
    tmp.insert(0, "case", name)
    
    winner = tmp.loc[0, device_col]
    winner_score = tmp.loc[0, 'score']
    
    print(f"\n=== {name} ===")
    print(f"weights: {weights}")
    print(f"winner: {winner} (score={winner_score:.4f})")
    if exclude_devices:
        print(f"excluded: {exclude_devices}")
    print(tmp[["rank", device_col, "score"]].to_string(index=False))
    
    return tmp

# --------------------------
# UDS (S1~S5) - All devices included
# --------------------------
print("\n" + "="*80)
print("UDS (S1~S5) - All 7 devices")
print("="*80)

all_results = []
winner_results = []

for name, w in UDS_profiles.items():
    result = run_profile(name, w, penalize_missing=True)
    all_results.append(result)
    
    # Winner info
    winner_results.append({
        "case": name,
        "type": "UDS_Basic",
        "device": result.loc[0, device_col],
        "score": result.loc[0, "score"],
        "n_devices": len(result)
    })

# --------------------------
# UDS_Extended (S1~S7) - Excluding Apple M4 CPU/ANE
# --------------------------
print("\n\n" + "="*80)
print("UDS_Extended (S1~S7) - Excluding Apple M4 CPU/ANE (5 devices)")
print("="*80)

# Devices to exclude (lacking power/compute specs)
EXCLUDE_APPLE_M4 = ['Apple M4 CPU', 'Apple M4 ANE']

for name, w in EXT_profiles.items():
    result = run_profile(name, w, penalize_missing=True, exclude_devices=EXCLUDE_APPLE_M4)
    all_results.append(result)
    
    # Winner info
    winner_results.append({
        "case": name,
        "type": "UDS_Extended",
        "device": result.loc[0, device_col],
        "score": result.loc[0, "score"],
        "n_devices": len(result)
    })

# --------------------------
# Save results to CSV
# --------------------------
print("\n\n" + "="*80)
print("Saving results to CSV...")
print("="*80)

# All results (16 cases × devices)
all_results_df = pd.concat(all_results, ignore_index=True)
all_results_df.to_csv(OUTPUT_UDS_CASES, index=False)
print(f"[OK] All case results saved to: {OUTPUT_UDS_CASES}")
print(f"  Total rows: {len(all_results_df)}")

# Winner summary
winner_df = pd.DataFrame(winner_results)
winner_df.to_csv(OUTPUT_UDS_WINNERS, index=False)
print(f"[OK] Winner summary saved to: {OUTPUT_UDS_WINNERS}")
print(f"  Total cases: {len(winner_df)}")

# Weight profiles summary
weight_profiles = []

# UDS (S1~S5) profiles
for name, weights in UDS_profiles.items():
    row = {
        "case": name,
        "type": "UDS_Basic",
        "S1": weights.get("S1", 0.0),
        "S2": weights.get("S2", 0.0),
        "S3": weights.get("S3", 0.0),
        "S4": weights.get("S4", 0.0),
        "S5": weights.get("S5", 0.0),
        "S6": 0.0,
        "S7": 0.0,
    }
    weight_profiles.append(row)

# UDS_Extended (S1~S7) profiles
for name, weights in EXT_profiles.items():
    row = {
        "case": name,
        "type": "UDS_Extended",
        "S1": weights.get("S1", 0.0),
        "S2": weights.get("S2", 0.0),
        "S3": weights.get("S3", 0.0),
        "S4": weights.get("S4", 0.0),
        "S5": weights.get("S5", 0.0),
        "S6": weights.get("S6", 0.0),
        "S7": weights.get("S7", 0.0),
    }
    weight_profiles.append(row)

weight_profiles_df = pd.DataFrame(weight_profiles)
weight_profiles_df.to_csv(OUTPUT_WEIGHT_PROFILES, index=False)
print(f"[OK] Weight profiles saved to: {OUTPUT_WEIGHT_PROFILES}")
print(f"  Total profiles: {len(weight_profiles_df)}")

print("\n" + "="*80)
print("Analysis completed!")
print("="*80)
